select_period: |
  Выберите за какой период времени вы хотите получить отчет
report: |
  Ваши расходы и доходы за <b>{period}:</b>
  Доход: {income} р.
  Расход: {expenses} р.
  
  Детализация расходов:
  {expenses_by_category}
  
  Остаток от дохода: {remaining_income} р.
  Остаток от общей суммы за выбранный период: {total_sum} р.
report_emoji: |
  📑
menu: |
  <b>Меню</b>