enter_amount: |
  Введите сумму:
select_category: |
  Выберите категорию:
no_categories: |
  У вас нет категорий. Сначала добавьте категории в разделе 'Категории'.
confirm_transaction: |
  Подтвердите добавление транзакции:
  Сумма: {amount} руб.
  Категория: {category}